### ISSUE TITLE
Update MQTT API compatibility with ESP32-S2

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_AdafruitIO#52]
This issue is **blocking** while I work on an updated MiniMQTT library release.

[The HTTP API in this library will be updated before MiniMQTT](https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/51), please use the HTTP examples for now.

**Comment by eukrit** [comment]
Hi brentru,

I wonder if this pending work is related to the esp initialization with SPI port with MagTag ESP32-S2?
I've attached a screenshot for reference.

![2021-01-19_1-15-43](https://user-images.githubusercontent.com/36352296/104952944-10969e80-59f8-11eb-87e5-c02159b7f632.jpg)

**Comment by FoamyGuy** [comment]
The code in your screenshot is importing and attempting to use `esp32spi` which is the library for dealing with ESP32 wifi co-processor devices, sometimes referred to "Airlift" on Adafruit devices.

It's not for the newer ESP32-S2 based devices like the MagTag

The error highlighted at the bottom is indicating that `boad.ESP_CS` does not exist on your device. ESP_CS would be the chip select pin for communicating with the wifi co-processor. Since the MagTag is ESP32-S2, and doesn't have the coprocessor, it also does not have or need an ESP_CS pin. So the error would be expected on that device I think.

**Comment by eukrit** [comment]
Thanks foamyguy, the next question form me is how to use MQTT with MagTag that had ESP32-S2 chipset?

**Comment by askpatrickw** [comment]
@eukrit follow this issue which is for the MiniMQTT work for ESP32S2 
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/43

**Comment by brentru** [comment]
I've released v5.0.0 of MiniMQTT which adds support for native networking. I'll update the Adafruit IO CircuitPython client to use this new release soon and incl. examples for ESP32S2 networking

**Comment by cluelesscris** [comment]
Excellent news.  I look forward to giving it a go.  Much appreciated.

**Comment by brentru** [comment]
Compatibility for ESP32-S2 added in v5.2.0 of this library

https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/releases/tag/5.2.0
